using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.IO;
using System.Xml;

namespace sample
{
    public partial class WebForm1 : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            string file = Path.Combine(Request.PhysicalApplicationPath, @"App_Data\Cars.xml");
            
            FileStream fs = new FileStream(file, FileMode.Create);

            XmlTextWriter w = new XmlTextWriter(fs, null);

            w.WriteStartDocument();
            w.WriteStartElement("Cars");
            w.WriteComment("This file is generated by the XmlTextWriter class.");
            w.WriteStartElement("Car");
            w.WriteAttributeString("ID", "1");
            w.WriteAttributeString("Name", "I20");
            w.WriteAttributeString("Make", "Hyundai");
            w.WriteStartElement("Price");
            w.WriteString("700000");
            w.WriteEndElement();
            w.WriteEndElement();
            w.WriteEndElement();
            w.WriteEndDocument();
            w.Close();
        }
    }
}